/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/PJSfe7Ym7SO
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function FriendList() {
  return (
    (<Card className="w-full max-w-md">
      <CardContent className="space-y-4 p-6 max-h-[300px] overflow-auto">
        <button
          className="flex items-center w-full space-x-4 rounded-md border p-2 hover:bg-muted bg-cover bg-center border-1"
          style={{ backgroundImage: "url('/bgbanner.jpg')" }}
          >
          <Avatar>
              <AvatarImage src="https://github.com/shadcn.png" />
              <AvatarFallback>CN</AvatarFallback>
            </Avatar>
          <div>
            <p className="font-medium">Acme Coder</p>
            <p className="text-muted-foreground text-sm">Software Engineer</p>
          </div>
        </button>
        <button
          className="flex items-center w-full space-x-4 rounded-md border p-2 hover:bg-muted bg-cover bg-center border-1"
          style={{ backgroundImage: "" }}>
         <Avatar>
              <AvatarImage src="https://github.com/shadcn.png" />
              <AvatarFallback>CN</AvatarFallback>
            </Avatar>
          <div>
            <p className="font-medium">Jared Palmer</p>
            <p className="text-muted-foreground text-sm">Product Designer</p>
          </div>
        </button>
        <button
           className="flex items-center w-full space-x-4 rounded-md border p-2 hover:bg-muted bg-cover bg-center border-1"
           style={{ backgroundImage: "" }}>
         <Avatar>
              <AvatarImage src="https://github.com/shadcn.png" />
              <AvatarFallback>CN</AvatarFallback>
            </Avatar>
          <div>
            <p className="font-medium">Shu Ding</p>
            <p className="text-muted-foreground text-sm">Frontend Engineer</p>
          </div>
        </button>
        <button
          className="flex items-center w-full space-x-4 rounded-md border border-1 p-2 hover:bg-muted bg-cover bg-center "
          style={{ backgroundImage: "url('')" }}>
          <Avatar>
              <AvatarImage src="https://github.com/shadcn.png" />
              <AvatarFallback>CN</AvatarFallback>
            </Avatar>
          <div>
            <p className="font-medium">Max Leiter</p>
            <p className="text-muted-foreground text-sm">Backend Engineer</p>
          </div>
        </button>
      </CardContent>
    </Card>)
  );
}
