/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/TfKHakkrAC4
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogTrigger, DialogContent } from "@/components/ui/dialog";

export function PostContent({ content }) {
  return (
    <section className="w-full max-w-md">
      {content ? <article className="">{content}</article> : null}
      {/* <Dialog>
        <DialogTrigger asChild>
          <div className="cursor-pointer">
            <img
              src={img}
              width={600}
              height={400}
              alt="Post Image"
              className="object-cover aspect-[3/4] w-full"
            />
          </div>
        </DialogTrigger>
        <DialogContent className="bg-background p-0 max-w-[90vw] max-h-[90vh] overflow-auto">
          <img
            src={img}
            width={1200}
            height={800}
            alt="Expanded Post Image"
            className="object-contain w-full"
          />
        </DialogContent>
      </Dialog> */}
    </section>
  );
}
